name: Github Actions Tests

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
      - run: |
          docker build -t test .
